# Generated by Django 5.1.5 on 2025-02-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
